movies/urls.py
from django.urls import path

from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.MovieListView.as_view(), name='index'),
    path('search/', views.search_movies, name='search'),
    path('create/', views.create_movie, name='create'),
    path('<int:movie_id>/', views.detail_movie, name='detail'),
    path('update/<int:movie_id>/', views.update_movie, name='update'),
    path('delete/<int:movie_id>/', views.delete_movie, name='delete'),
    path('<int:movie_id>/review/', views.create_review, name='review'),
    path('lists/', views.ListListView.as_view(), name='lists'),
    path('lists/create', views.ListCreateView.as_view(), name='create-list'),
]

moviesite/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('staticpages.urls')),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')), # adicionar esta linha
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')) #inclui varias urls que vem padrao
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | Watch that film!
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>

<body>
    <header id="cabecalho-principal">
        <a href="{% url 'index' %}"> <img src="{% static 'logo.svg' %}"> </a>
        <nav id="navegacao-principal">
            <ul>
                {% if user.is_authenticated %}
                    <li> Logado com {{ user.username }} </li>
                    <li><a href="{% url 'logout' %}">Log out</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}">Log in</a></li>
                {% endif %}
                <li><a href="{% url 'movies:index' %}">Filmes</a></li>
                <li><a href="{% url 'movies:lists' %}">Listas</a></li>
                <li><a href="{% url 'about' %}">Sobre</a></li>
            </ul>
        </nav>

    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>Copyright 2021</small>
        </p>
    </footer>
</body>

</html>